### ISSUE TITLE
Bleeding edge API?

### ISSUE THREAD

**Issue by maximsko** [bwillis/versioncake#43]
How would I create an edgy API, which is basically in a WIP status? Optimally, I would would want to call something like http://localhost:3000/api/posts.json and get the bleeding edge json from views/posts/index.json.jbuilder (without specifying any version) and / or alternatively call http://localhost:3000/api/edge/posts.json and get the result from the same file.

**Comment by bwillis** [comment]
Hey @maximski,

You can set a configuration setting called `missing_version` (in previous versions of versioncake it was called `default_version`) to point a WIP version number. To me, that feels like the most explicit way to develop your next API version.

Let me know if that answers your question!

**Comment by maximski** [comment]
Hi, sorry for the late answer!

It's not exactly what I am looking for. I can't use a string ("edge") for that configuration setting, because it will complain about a String to Fixnum comparison (I am considering to catch the :api_version parameter before versioncake gets it and to rewrite the edge to a number, but I don't already like that approach as a thought).

Also, I think the versionless .jbuilder files (like show.json.jbuilder) should be used for the latest version (cause they are the state of art). Right now a show.json.v4.jbuilder will be prioritized over a show.json.v5.jbuilder if just `config.missing_version = 4`is set. But I guess that's quite opinionated by me and not too relevant in the real world.

**Comment by bwillis** [comment]
> that's quite opinionated by me and not too relevant in the real world

Opinionated, yes, not relevant, I disagree :smile:. I think using the unversioned template is pretty similar to a workflow I was using on a past API and I think it does have it's benefits, but I'm not sure using the unversioned templates automatically is immediately obvious. Maybe there is something we can do in configuration to make this more explicit:
```ruby
config.missing_version = :unversioned_template
```
What do you think?

**Comment by maximski** [comment]
I think that sounds like a fitting solution :) Thanks for your commitment!
