### ISSUE TITLE
semantic versioning?

### ISSUE THREAD

**Issue by devpopol** [bwillis/versioncake#46]
hey @bwillis, does versioncake support semantic version numbers for versioning ones api? seeing that the version numbers directly maps to the views(e.g.: `index.xml.v1.builder`) -- it may be a challenge to do something like: `index.xml.v1.0.3.builder` ? or is there some `render` method it provides that would allow one to render a template by name(e.g. render "show", :version => "1.0.3" )?

**Comment by bwillis** [comment]
Sorry for the delayed response! From what I see most APIs don't publish patch or minor version because, in semantic versioning, these _shouldn't_ break anything. So for example, if I request `v1` of an API I might actually be getting `v1.0.3`. So in this way, I would say it does support semantic versioning by making non breaking changes (aka minor and patch) to you `index.xml.v1.builder` and then bumping to `index.xml.v2.builder` when you introduce breaking changes. What are your thoughts?

**Comment by devpopol** [comment]
hey @bwillis, thanks for taking the time to respond. I'm thinking that it may be a bit limiting to not be able to do that. I think it's necessary when you want to offer consistency with what you return. Because, while you can make changes that doesn't introduce "breaking changes" to the api per se, the clients can(or provided sdks, as the case may be) break while consuming it. For example, a client code consuming the api traverses an xml in a sort of bad way:

example output format for v1.0.0:
```xml
<TheTransaction>
    <from>123123123</from>
    <to>3213212312</to>
    <created-at>1457998718</created-at>
</TheTransaction>
```
consider a client with the code:
```javascript
parser = new DOMParser();
xmlDoc = parser.parseFromString(text,"text/xml");

x = xmlDoc.documentElement.childNodes;
var fromAccount = x[0].nodeValue;
var toAccount = x[1].nodeValue;
var createdAt = x[2].nodeValue;
```

and in v1.0.1:
```xml
<TheTransaction>
    <from>123123123</from>
    <fromName>devpopol</from>
    <to>3213212312</to>
    <created-at>1457998718</created-at>
</TheTransaction>
```

With this new output, the xml client would break. With people writing their own clients, it would be difficult to guarantee that when you update your api, things won't break for any of them. Or if you provide an sdk, to guarantee that it still works, you'll have to take all old releases(for `v1`) and test them to make sure. Apologies if the example is a little silly -- just trying to give an example why this can be a thing. Because stakeholders may care about not having to waste time helping people to "unbreak" their code.

The ideal situation i think would probably be to have 2 endpoints, one for `v1.0.0` and one for `v1.0.1` with their corresponding return formats(and all other endpoints in `v1.0.1` default to `v1.0.0`). And one can say to customers:

* the sdk released for `v1.0.0` may(or most likely) still work for `v1.0.1` but it's not guaranteed. get the sdk for v1.0.1(because we've tested that against it)
* v1.0.0 is still supported(meaning, existing clients are guaranteed to work, including our sdk that uses `v1.0.0`)

Please let me know your thoughts about it. Thanks!

**Comment by bwillis** [comment]
I think this is the part that is always subjective. In my experience, additive changes are "backwards compatible", but you are correct that it's always depends on your client implementations. Some client implementors like to be extremely strict, using XSLTs and other things for verification, while others are very forgiving in their implementation. Maybe you can influence this by having client best practices to support how you will be versioning, for example: use XPath instead of relying on node ordering.

So in your example, if you feel that the change for `v1.0.1` is breaking to you clients, I would change it to `v2`. I think an important reason for this, depending on your strategy, is maintenance of old versions. Let's say you found a major bug or security vulnerability, you have to go back and patch existing versions, so `v1.0.0` => `v1.0.1` and `v2.0.0` => `v2.0.1` get applied to clients immediately. In your case I could see versions getting confusing.

Let me know if this makes sense!

**Comment by bwillis** [comment]
Going to close this out for now.
