### ISSUE TITLE
Guidance on skipping versioning for routes by controller class

### ISSUE THREAD

**Issue by hlascelles** [bwillis/versioncake#69]
We are upgrading from v2, and use a custom version extraction strategy. We employ a number of engines which service certain requests, eg Devise and PGHero, and server a number of pages from a `PagesController`.

For these engines and controllers, there is no versioning. In our current custom version extraction strategy we used to just ask the `ActionDispatch::Request` object for the controller class thus: `controller = request.params[:controller]`
This meant we could "use latest version" (skip versioning) for any related calls by checking against a short list of controller classes.

Now, in v3, the request object no longer has that param, it is a raw `Rack::Request`. We only have the uri to work with.  Does this mean maintaining a list of versioncake `resource` regexes for third party engines, and all "pages"?

How do you recommend skipping versioning by controller class? Note, some of the controllers "aren't ours" (as they are engines).

**Comment by bwillis** [comment]
Thanks for the question, let me see if I can help.

Some quick context and a lot of this you discovered on your own, so this is more for reminding myself. So, as you noticed, v2 to v3 was a restructuring in order to gain more a bit more flexibility by moving VersionCake into middleware, but one of the tradeoffs was extraction strategies now have to deal with a simpler (and more basic by Rails standards) `Rack::Request`. We also added more explicit declaration of [Version Resources](https://github.com/bwillis/versioncake#versioned-resources), you have to do more work around explicitly defining your versions, but if a route is not a versioned resource, it will be skipped and the request is undisturbed. 

To your specific question, I'm making an assumption that your engines are mounted like so:
```
# routes.rb
mount Sidekiq::Web => '/sidekiq'
```
So that would mean explicitly not adding that route to the version resources. At a high level, I think this is the answer, but I expect you have some additional context that makes this a bit more complex 😄  so let me know if I didn't answer your question!

**Comment by hlascelles** [comment]
Yes, that makes sense about the rewrite, I got as far as determining it was now middleware, but thought I'd stop investigating until I'd asked you.

I can see how mounted engines could work easily on prefix. But we still have an issue with our own static pages.

We have dozens of resources and dozens of pages. We'd like to say "for all resources, use this set of versions, but for any static pages, don't use versioning". As far as I can tell that means we either have to explicitly iterate over all our resources' paths, or over all our static pages' paths. If any of those have a custom route, and some do of each, then they must all be declared explicitly too. Is that correct?

I would prefer to say (pseudo code)...

```ruby
  config.resources do |r|
    r.resource PagesController :none       # <= Covers a very large selection of ever-changing paths
    r.resource Sidekiq::Controller :none   # <= Covers paths we may not even be aware of (though we could use a path prefix here)
    r.resource %r{.*}, [], [], (1..4)      # <= "everything else" (ie our API).
  end
```

Does that capture it?

**Comment by bwillis** [comment]
Yeah that makes sense. The way resources are to be configured is with a whitelisted approach. Given your use case it seems that it would be easier to have a blacklist.  VersionCake wants to work with just the exact resources and meta data during each request, so we need to, at some point, have the explicit list. Perhaps we can leverage Rails a bit to start with the full list and remove the parts we don't want and they come up with the explicit list of resources, off the top of my head I wonder if something like this is possible:
```ruby
resource_regex_paths = Rails.application.routes.routes.select |route|
    %w(/user/:id /user).exclude? route.path.spec
end
config.resources do |r|
  resource_regex_paths.each do |path|
    r.resource route.path.spec, [], [], (1..4)
  end
end
```
A few problems to deal with above:
 - it sounds like you want controller instead of paths, so figuring out how to derived it from controllers
 - `route.path.spec` is not a regex, so there'd need some massaging to get it into the right format
 - less flexibility of bumping individual resource versions

Does something like that give you an option to move forward?

**Comment by hlascelles** [comment]
Thanks, yes, that does look like it will work... 

We're now in the process of seeing how much of a migration it will be compared to just adding ad hoc internal versioning. We typically have forward compatible intra-service payloads anyway, so we may choose to cater for individual fields as they arise. If we come up with other ideas we will add them here. Cheers!

**Comment by hlascelles** [comment]
We have managed to migrate everything to rack based checks. Thanks for your guidance!
